apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-service-config
  labels:
    app.kubernetes.io/name: customer-service
    app.kubernetes.io/part-of: fiap-tech-challenge
data:
  NODE_ENV: "production"
  PORT: "3000"
  SERVICE_NAME: "customer-service"
  SERVICE_VERSION: "0.1.0"
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  JWT_ISSUER: "fiap-tech-challenge-auth-function"
  JWT_AUDIENCE: "fiap-tech-challenge-api"
  JWT_REQUIRED_CUSTOMER_STATUS: "ACTIVE"
  DB_HOST: "replace-with-managed-mysql-endpoint"
  DB_PORT: "3306"
  DB_DATABASE: "customer_service"
  DB_SSL: "true"
  MESSAGING_ENABLED: "true"
  RABBITMQ_MAX_RETRIES: "3"
  METRICS_ENABLED: "true"
