apiVersion: v1
kind: Secret
metadata:
  name: customer-service-secret
  labels:
    app.kubernetes.io/name: customer-service
    app.kubernetes.io/part-of: fiap-tech-challenge
type: Opaque
stringData:
  JWT_SECRET: "${JWT_SECRET}"
  DB_USERNAME: "${CUSTOMER_DB_USERNAME}"
  DB_PASSWORD: "${CUSTOMER_DB_PASSWORD}"
